### ISSUE TITLE
FilterNode uses this, but is static

### ISSUE THREAD

**Issue by daryllabar** [SimplerSoftware/XrmTSToolkit#1]
``` TypeScript
public static FilterNode = function (name) {
    return this.find('*').filter(function () {
        return this.nodeName === name;
    });
};
```

**Comment by StevenRasmussen** [comment]
Hi Daryl, thanks for pointing this out.  I'm not really even sure why this method is in there to be honest.  I must have ported it from another library but it's not even being used.  I have removed it from the source and will be pushing an update here soon.

**Comment by StevenRasmussen** [comment]
Removed method in v0.8.0
