### ISSUE TITLE
Use of our registered company name

### ISSUE THREAD

**Issue by johnwc** [SimplerSoftware/XrmTSToolkit#10]
Simpler Software is our registered company name. Can we kindly ask you to please change the name you are using so that we can move forward with using our company name as a organization on GitHub?

**Comment by StevenRasmussen** [comment]
Hi John, we also have a registered company name of Simpler Software which is why we have the name on GitHub :)  I apologize for any inconvenience.

**Comment by johnwc** [comment]
I'm sorry, but you don't have it registered. Only one entity can have a name registered and copyrighted. You may have it DBA'd in your local county. We have had a LLC with it and had the domain also registered for over 16 years.

**Comment by StevenRasmussen** [comment]
Hi John, perhaps we're not talking about the same kind of registration.  Anyway, let me clarify for you what I mean:  We are a registered company with the name 'Simpler Software LLC' (As far as I know you can have the same name as long as another company is not registered in the same state with the same name).  We have been doing business for the last 7 years using this name.  We own the domain 'simpler-software.com' (although nothing is parked there).  We have other websites for specific products that we sell.  I checked the US Trademark website to see if the name 'Simpler Software' had been trademarked and I did not see anything that indicated that it was a registered trademark (Names or simple phrases cannot be copyrighted, see here [https://www.copyright.gov/circs/circ34.pdf](https://www.copyright.gov/circs/circ34.pdf)).  Again, I apologize for any inconvenience but as far as I can tell we have just as much of a right to use this name as you do.
