### ISSUE TITLE
QualifyLeadRequest's EntityReferenceCollection not working correctly

### ISSUE THREAD

**Issue by daryllabar** [SimplerSoftware/XrmTSToolkit#2]
I implemented a Qualify Lead Request.  It's response type includes an EntityReferenceCollection.  When parsing the result, the Last Entity Reference in the Collection is the only thing that gets returned.

These are some of the changes I had to implement to get it to work.

Added a EntityReferenceCollection Type:

``` typescript
type EntityReferenceCollection = Array<Soap.EntityReference>;
```

Added an EntityReferenceCollection Case in GetObjectFromBaseXRMObject:

``` typescript
case "EntityReferenceCollection":
    CurrentObject = new Array<Soap.EntityReference>();
    break;
```

Added the Request and Response classes:

``` typescript
export class QualifyLeadRequest extends ExecuteRequest {

    constructor(
        CreateAccount: boolean,
        CreateContact: boolean,
        CreateOpportunity: boolean,
        LeadId: EntityReference,
        SourceCampaignId?: EntityReference,
        OpportunityCurrencyId?: EntityReference,
        OpportunityCustomerId?: EntityReference
    ) {
        super("QualifyLead");
        this.Parameters["CreateAccount"] = new BooleanValue(CreateAccount);
        this.Parameters["CreateContact"] = new BooleanValue(CreateContact);
        this.Parameters["CreateOpportunity"] = new BooleanValue(CreateOpportunity);
        this.Parameters["LeadId"] = LeadId;
        if (OpportunityCurrencyId) {
            this.Parameters["OpportunityCurrencyId"] = OpportunityCurrencyId;
        }
        if (OpportunityCustomerId) {
            this.Parameters["OpportunityCustomerId"] = OpportunityCustomerId;
        }
        if (SourceCampaignId) {
            this.Parameters["SourceCampaignId"] = SourceCampaignId;
        }
        this.Parameters["Status"] = new OptionSetValue(3); // Qualified
    }
}
export class QualifyLeadResponse extends ExecuteResponse {
    CreatedEntities: EntityReferenceCollection;
}
```

[I've done a lot of formatting changes as well](https://github.com/daryllabar/XrmTSToolkit/commit/df8c791201512fbdec49a7bf386788c3846d8ca0), but you probably won't care about them, and they don't apply to this issue.  I just had to organize the code a little to understand why I what was happening.  If you'd like a pull request, I'd love to give it to you and abandon my branch, but again, don't think that makes since.

**Comment by StevenRasmussen** [comment]
Hi Daryl, thanks for the info.  I've gone ahead and added in the 'EntityReferenceCollection' in v0.8.0 that I just committed.  There are quite a few changes that have been added so you'll want to take a look.

**Comment by daryllabar** [comment]
What are the new features with your changes?

**Comment by StevenRasmussen** [comment]
Features include being able to query for metadata, using a 'string' and 'boolean' for attribute values instead of creating a 'StringValue' and 'BooleanValue'.  However, when retrieving from CRM they will always come back as a 'BooleanValue' and 'StringValue'.  There was quite a bit of refactoring and just general code cleanup.  For more info see the comments at the top of the XrmTSToolkit.ts file.
