### ISSUE TITLE
Soap Module Listed twice?

### ISSUE THREAD

**Issue by daryllabar** [SimplerSoftware/XrmTSToolkit#6]
Any reason the Soap Module is listed twice:

![image](https://cloud.githubusercontent.com/assets/9728423/13670709/6ac663ea-e699-11e5-974a-b4d71f196495.png)

Ever thought of using [Gitter](https://gitter.im/)?  This type of post is really more of a discussion, and doesn't really belong as an "issue" IMHO.  It's been very helpful for the [XrmToolBox](https://gitter.im/MscrmTools/XrmToolBox)

**Comment by StevenRasmussen** [comment]
Not really.  It was more just for logical separation of some of the code but it can be consolidated into one location.  I think that makes sense to just have it in one location so I'll consolidate in the next release.
